### ISSUE TITLE
create a Code of Conduct

### ISSUE THREAD

**Issue by drtortoise** [drtortoise/critical-algorithm-studies#4]

**Comment by gabelula** [comment]
What about adapting the one from srccon? http://srccon.org/conduct/

**Comment by drtortoise** [comment]
@Algorithm_Club is committed to providing a welcoming and harassment-free environment for participants of all races, gender and trans statuses, sexual orientations, physical abilities, physical appearances, and beliefs. We’ve written this code of conduct not because we expect bad behavior from our community—which, in our experience, is overwhelmingly kind and civil—but because we believe a clear code of conduct is one necessary part of building a respectful community space.
@Algorithm_Club participants agree to:
Be considerate in speech and actions, and actively seek to acknowledge and respect the boundaries of fellow attendees.
Refrain from demeaning, discriminatory, or harassing behavior and speech. Harassment includes, but is not limited to: deliberate intimidation; stalking; use of sexual or discriminatory imagery, comments, or jokes; and unwelcome sexual attention. If you feel that someone has harassed you or otherwise treated you inappropriately, please alert @algorithm_club via dm.
Take care of each other. Alert @algorithm_club if you notice a dangerous situation, someone in distress, or violations of this code of conduct, even if they seem inconsequential.
If any person engages in harassing behavior, the @algorithm_club may take any lawful action we deem appropriate, including but not limited to blocking the person from attending @algorithm_club. 
We welcome your feedback on this and every other aspect of @algorithm_club, and we thank you for working with us to make it a safe, enjoyable, and friendly experience for everyone who participates.
Above text is licensed CC BY-SA 4.0. Credit to Citizen Code of Conduct, the Django Project’s code of conduct and Theorizing the Web code of conduct from which we’ve extensively borrowed, with general thanks to the Ada Initiative’s “how to design a code of conduct for your community.”

**Comment by drtortoise** [comment]
closing this issue, but the CoC is still open for discussion and amendment
